title:              Shanghai CaiZhi Paper
email:              shcz@vip.163.com
description:        Shanghai CaiZhi Paper
author:             Loky Mo
baseurl:            ""
url:                "https://JekyllSite-LokyMo.icom101.repl.co"

# Social Profiles
wechat_username:  Caizhi Paper 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

destination: ../docs